DEF NUM_PLAYER_NAMES EQU 4

; Nemesis intro name suggestions. Gen 1 caps names at PLAYER_NAME_LENGTH - 1 = 7
; characters, so every entry here must be <= 7 chars (the `li` macro asserts it).
IF DEF(_RED)
DEF PLAYERNAME1 EQUS "HIRO"
DEF PLAYERNAME2 EQUS "PLUTO"
DEF PLAYERNAME3 EQUS "JAX"
DEF PLAYERNAME4 EQUS "ARGENT"

DEF RIVALNAME1 EQUS "KATAKI"
DEF RIVALNAME2 EQUS "SATURN"
DEF RIVALNAME3 EQUS "DEX"
DEF RIVALNAME4 EQUS "VERMEIL"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "HIRO"
DEF PLAYERNAME2 EQUS "PLUTO"
DEF PLAYERNAME3 EQUS "JAX"
DEF PLAYERNAME4 EQUS "ARGENT"

DEF RIVALNAME1 EQUS "KATAKI"
DEF RIVALNAME2 EQUS "SATURN"
DEF RIVALNAME3 EQUS "DEX"
DEF RIVALNAME4 EQUS "VERMEIL"
ENDC
