SSOlympiaB1FRooms_Script:
	call EnableAutoTextBoxDrawing
	ld hl, SSOlympiaB1FRoomsTrainerHeaders
	ld de, SSOlympiaB1FRooms_ScriptPointers
	ld a, [wSSOlympiaB1FRoomsCurScript]
	call ExecuteCurMapScriptInTable
	ld [wSSOlympiaB1FRoomsCurScript], a
	ret

SSOlympiaB1FRooms_ScriptPointers:
	def_script_pointers
	dw_const CheckFightingMapTrainers,              SCRIPT_SSOLYMPIAB1FROOMS_DEFAULT
	dw_const DisplayEnemyTrainerTextAndStartBattle, SCRIPT_SSOLYMPIAB1FROOMS_START_BATTLE
	dw_const EndTrainerBattle,                      SCRIPT_SSOLYMPIAB1FROOMS_END_BATTLE

SSOlympiaB1FRooms_TextPointers:
	def_text_pointers
	dw_const SSOlympiaB1FRoomsSuperNerdText, TEXT_SSOLYMPIAB1FROOMS_SUPER_NERD
	dw_const SSOlympiaB1FRoomsMachokeText, TEXT_SSOLYMPIAB1FROOMS_MACHOKE
	dw_const PickUpItemText, TEXT_SSOLYMPIAB1FROOMS_ETHER
	dw_const PickUpItemText, TEXT_SSOLYMPIAB1FROOMS_TM_REST
	dw_const PickUpItemText, TEXT_SSOLYMPIAB1FROOMS_MAX_POTION
	dw_const SSOlympiaB1FRoomsTobyText, TEXT_SSOLYMPIAB1FROOMS_TOBY
	dw_const SSOlympiaB1FRoomsOakText, TEXT_SSOLYMPIAB1FROOMS_OAK
	dw_const SSOlympiaB1FRoomsNerdText, TEXT_SSOLYMPIAB1FROOMS_NERD
	dw_const SSOlympiaB1FRoomsEngineerText, TEXT_SSOLYMPIAB1FROOMS_ENGINEER
	dw_const SSOlympiaB1FRoomsPsychicTrText, TEXT_SSOLYMPIAB1FROOMS_PSYCHICTR

SSOlympiaB1FRoomsTrainerHeaders:
	def_trainers 5
SSOlympiaB1FRoomsTrainerHeader0:
	trainer EVENT_BEAT_SS_OLYMPIA_B1FROOMS_TRAINER_0, 3, SSOlympiaB1FRoomsTobyBattleText, SSOlympiaB1FRoomsTobyEndBattleText, SSOlympiaB1FRoomsTobyAfterBattleText
SSOlympiaB1FRoomsTrainerHeader1:
	trainer EVENT_BEAT_SS_OLYMPIA_B1FROOMS_TRAINER_1, 3, SSOlympiaB1FRoomsOakBattleText, SSOlympiaB1FRoomsOakEndBattleText, SSOlympiaB1FRoomsOakAfterBattleText
SSOlympiaB1FRoomsTrainerHeader2:
	trainer EVENT_BEAT_SS_OLYMPIA_B1FROOMS_TRAINER_2, 3, SSOlympiaB1FRoomsNerdBattleText, SSOlympiaB1FRoomsNerdEndBattleText, SSOlympiaB1FRoomsNerdAfterBattleText
SSOlympiaB1FRoomsTrainerHeader3:
	trainer_in wOlympiaTrainerFlags, 16, 2, SSOlympiaB1FRoomsEngineerBattleText, SSOlympiaB1FRoomsEngineerEndBattleText, SSOlympiaB1FRoomsEngineerAfterBattleText
SSOlympiaB1FRoomsTrainerHeader4:
	trainer_in wOlympiaTrainerFlags, 17, 2, SSOlympiaB1FRoomsPsychicTrBattleText, SSOlympiaB1FRoomsPsychicTrEndBattleText, SSOlympiaB1FRoomsPsychicTrAfterBattleText
	db -1 ; end

SSOlympiaB1FRoomsSuperNerdText:
	text_far _SSOlympiaB1FRoomsSuperNerdText
	text_end

SSOlympiaB1FRoomsMachokeText:
	text_far _SSOlympiaB1FRoomsMachokeText
	text_end
SSOlympiaB1FRoomsTobyText:
	text_asm
	ld hl, SSOlympiaB1FRoomsTrainerHeader0
	call TalkToTrainer
	jp TextScriptEnd

SSOlympiaB1FRoomsOakText:
	text_asm
	ld hl, SSOlympiaB1FRoomsTrainerHeader1
	call TalkToTrainer
	jp TextScriptEnd

SSOlympiaB1FRoomsNerdText:
	text_asm
	ld hl, SSOlympiaB1FRoomsTrainerHeader2
	call TalkToTrainer
	jp TextScriptEnd


SSOlympiaB1FRoomsTobyBattleText:
	text_far _SSOlympiaB1FRoomsTobyBattleText
	text_end

SSOlympiaB1FRoomsTobyEndBattleText:
	text_far _SSOlympiaB1FRoomsTobyEndBattleText
	text_end

SSOlympiaB1FRoomsTobyAfterBattleText:
	text_far _SSOlympiaB1FRoomsTobyAfterBattleText
	text_end

SSOlympiaB1FRoomsOakBattleText:
	text_far _SSOlympiaB1FRoomsOakBattleText
	text_end

SSOlympiaB1FRoomsOakEndBattleText:
	text_far _SSOlympiaB1FRoomsOakEndBattleText
	text_end

SSOlympiaB1FRoomsOakAfterBattleText:
	text_far _SSOlympiaB1FRoomsOakAfterBattleText
	text_end

SSOlympiaB1FRoomsNerdBattleText:
	text_far _SSOlympiaB1FRoomsNerdBattleText
	text_end

SSOlympiaB1FRoomsNerdEndBattleText:
	text_far _SSOlympiaB1FRoomsNerdEndBattleText
	text_end

SSOlympiaB1FRoomsNerdAfterBattleText:
	text_far _SSOlympiaB1FRoomsNerdAfterBattleText
	text_end

SSOlympiaB1FRoomsEngineerText:
	text_asm
	ld hl, SSOlympiaB1FRoomsTrainerHeader3
	call TalkToTrainer
	jp TextScriptEnd

SSOlympiaB1FRoomsEngineerBattleText:
	text_far _SSOlympiaB1FRoomsEngineerBattleText
	text_end

SSOlympiaB1FRoomsEngineerEndBattleText:
	text_far _SSOlympiaB1FRoomsEngineerEndBattleText
	text_end

SSOlympiaB1FRoomsEngineerAfterBattleText:
	text_far _SSOlympiaB1FRoomsEngineerAfterBattleText
	text_end

SSOlympiaB1FRoomsPsychicTrText:
	text_asm
	ld hl, SSOlympiaB1FRoomsTrainerHeader4
	call TalkToTrainer
	jp TextScriptEnd

SSOlympiaB1FRoomsPsychicTrBattleText:
	text_far _SSOlympiaB1FRoomsPsychicTrBattleText
	text_end

SSOlympiaB1FRoomsPsychicTrEndBattleText:
	text_far _SSOlympiaB1FRoomsPsychicTrEndBattleText
	text_end

SSOlympiaB1FRoomsPsychicTrAfterBattleText:
	text_far _SSOlympiaB1FRoomsPsychicTrAfterBattleText
	text_end
