SSOlympiaCaptainsRoom_Script:
	call EnableAutoTextBoxDrawing
	ld hl, SSOlympiaCaptainsRoomTrainerHeaders
	ld de, SSOlympiaCaptainsRoom_ScriptPointers
	ld a, [wSSOlympiaCaptainsRoomCurScript]
	call ExecuteCurMapScriptInTable
	ld [wSSOlympiaCaptainsRoomCurScript], a
	ret

SSOlympiaCaptainsRoom_ScriptPointers:
	def_script_pointers
	dw_const CheckFightingMapTrainers,              SCRIPT_SSOLYMPIACAPTAINSROOM_DEFAULT
	dw_const DisplayEnemyTrainerTextAndStartBattle, SCRIPT_SSOLYMPIACAPTAINSROOM_START_BATTLE
	dw_const EndTrainerBattle,                      SCRIPT_SSOLYMPIACAPTAINSROOM_END_BATTLE

SSOlympiaCaptainsRoom_TextPointers:
	def_text_pointers
	dw_const SSOlympiaCaptainsRoomFisherText, TEXT_SSOLYMPIACAPTAINSROOM_FISHER
	dw_const SSOlympiaCaptainsRoomBlackbeltText, TEXT_SSOLYMPIACAPTAINSROOM_BLACKBELT
	dw_const SSOlympiaCaptainsRoomTrashText, TEXT_SSOLYMPIACAPTAINSROOM_TRASH
	dw_const SSOlympiaCaptainsRoomLogbookText, TEXT_SSOLYMPIACAPTAINSROOM_LOGBOOK

SSOlympiaCaptainsRoomTrainerHeaders:
	def_trainers 6
SSOlympiaCaptainsRoomTrainerHeader0:
	trainer EVENT_BEAT_SS_OLYMPIA_CAPTAINS_ROOM_ROCKET_0, 3, SSOlympiaCaptainsRoomFisherBattleText, SSOlympiaCaptainsRoomFisherEndBattleText, SSOlympiaCaptainsRoomFisherAfterBattleText
SSOlympiaCaptainsRoomTrainerHeader1:
	trainer_in wOlympiaTrainerFlags, 15, 2, SSOlympiaCaptainsRoomBlackbeltBattleText, SSOlympiaCaptainsRoomBlackbeltEndBattleText, SSOlympiaCaptainsRoomBlackbeltAfterBattleText
	db -1 ; end

SSOlympiaCaptainsRoomTrashText:
	text_far _SSOlympiaCaptainsRoomTrashText
	text_end

SSOlympiaCaptainsRoomLogbookText:
	text_far _SSOlympiaCaptainsRoomLogbookText
	text_end
SSOlympiaCaptainsRoomFisherText:
	text_asm
	ld hl, SSOlympiaCaptainsRoomTrainerHeader0
	call TalkToTrainer
	jp TextScriptEnd


SSOlympiaCaptainsRoomFisherBattleText:
	text_far _SSOlympiaCaptainsRoomFisherBattleText
	text_end

SSOlympiaCaptainsRoomFisherEndBattleText:
	text_far _SSOlympiaCaptainsRoomFisherEndBattleText
	text_end

SSOlympiaCaptainsRoomFisherAfterBattleText:
	text_far _SSOlympiaCaptainsRoomFisherAfterBattleText
	text_end

SSOlympiaCaptainsRoomBlackbeltText:
	text_asm
	ld hl, SSOlympiaCaptainsRoomTrainerHeader1
	call TalkToTrainer
	jp TextScriptEnd

SSOlympiaCaptainsRoomBlackbeltBattleText:
	text_far _SSOlympiaCaptainsRoomBlackbeltBattleText
	text_end

SSOlympiaCaptainsRoomBlackbeltEndBattleText:
	text_far _SSOlympiaCaptainsRoomBlackbeltEndBattleText
	text_end

SSOlympiaCaptainsRoomBlackbeltAfterBattleText:
	text_far _SSOlympiaCaptainsRoomBlackbeltAfterBattleText
	text_end
