SSOlympia2FRooms_Script:
	call EnableAutoTextBoxDrawing
	ld hl, SSOlympia2FRoomsTrainerHeaders
	ld de, SSOlympia2FRooms_ScriptPointers
	ld a, [wSSOlympia2FRoomsCurScript]
	call ExecuteCurMapScriptInTable
	ld [wSSOlympia2FRoomsCurScript], a
	ret

SSOlympia2FRooms_ScriptPointers:
	def_script_pointers
	dw_const CheckFightingMapTrainers,              SCRIPT_SSOLYMPIA2FROOMS_DEFAULT
	dw_const DisplayEnemyTrainerTextAndStartBattle, SCRIPT_SSOLYMPIA2FROOMS_START_BATTLE
	dw_const EndTrainerBattle,                      SCRIPT_SSOLYMPIA2FROOMS_END_BATTLE

SSOlympia2FRooms_TextPointers:
	def_text_pointers
	dw_const PickUpItemText, TEXT_SSOLYMPIA2FROOMS_MAX_ETHER
	dw_const SSOlympia2FRoomsGrampsText, TEXT_SSOLYMPIA2FROOMS_GRAMPS
	dw_const PickUpItemText, TEXT_SSOLYMPIA2FROOMS_RARE_CANDY
	dw_const SSOlympia2FRoomsLittleBoyText, TEXT_SSOLYMPIA2FROOMS_LITTLE_BOY
	dw_const SSOlympia2FRoomsBrunetteGirlText, TEXT_SSOLYMPIA2FROOMS_BRUNETTE_GIRL
	dw_const SSOlympia2FRoomsBeautyText, TEXT_SSOLYMPIA2FROOMS_BEAUTY
	dw_const SSOlympia2FRoomsNormanText, TEXT_SSOLYMPIA2FROOMS_NORMAN
	dw_const SSOlympia2FRoomsGiovanniText, TEXT_SSOLYMPIA2FROOMS_GIOVANNI
	dw_const SSOlympia2FRoomsLoreleiText, TEXT_SSOLYMPIA2FROOMS_LORELEI
	dw_const SSOlympia2FRoomsPokemaniacText, TEXT_SSOLYMPIA2FROOMS_POKEMANIAC
	dw_const SSOlympia2FRoomsGamblerText, TEXT_SSOLYMPIA2FROOMS_GAMBLER

SSOlympia2FRoomsTrainerHeaders:
	def_trainers 2
SSOlympia2FRoomsTrainerHeader0:
	trainer EVENT_BEAT_SS_OLYMPIA_2FROOMS_TRAINER_0, 3, SSOlympia2FRoomsNormanBattleText, SSOlympia2FRoomsNormanEndBattleText, SSOlympia2FRoomsNormanAfterBattleText
SSOlympia2FRoomsTrainerHeader1:
	trainer EVENT_BEAT_SS_OLYMPIA_2FROOMS_TRAINER_1, 3, SSOlympia2FRoomsGiovanniBattleText, SSOlympia2FRoomsGiovanniEndBattleText, SSOlympia2FRoomsGiovanniAfterBattleText
SSOlympia2FRoomsTrainerHeader2:
	trainer EVENT_BEAT_SS_OLYMPIA_2FROOMS_TRAINER_2, 3, SSOlympia2FRoomsLoreleiBattleText, SSOlympia2FRoomsLoreleiEndBattleText, SSOlympia2FRoomsLoreleiAfterBattleText
SSOlympia2FRoomsTrainerHeader3:
	trainer_in wOlympiaTrainerFlags, 13, 2, SSOlympia2FRoomsPokemaniacBattleText, SSOlympia2FRoomsPokemaniacEndBattleText, SSOlympia2FRoomsPokemaniacAfterBattleText
SSOlympia2FRoomsTrainerHeader4:
	trainer_in wOlympiaTrainerFlags, 14, 2, SSOlympia2FRoomsGamblerBattleText, SSOlympia2FRoomsGamblerEndBattleText, SSOlympia2FRoomsGamblerAfterBattleText
	db -1 ; end

SSOlympia2FRoomsGrampsText:
	text_far _SSOlympia2FRoomsGrampsText
	text_end

SSOlympia2FRoomsLittleBoyText:
	text_far _SSOlympia2FRoomsLittleBoyText
	text_end

SSOlympia2FRoomsBrunetteGirlText:
	text_far _SSOlympia2FRoomsBrunetteGirlText
	text_end

SSOlympia2FRoomsBeautyText:
	text_far _SSOlympia2FRoomsBeautyText
	text_end
SSOlympia2FRoomsNormanText:
	text_asm
	ld hl, SSOlympia2FRoomsTrainerHeader0
	call TalkToTrainer
	jp TextScriptEnd

SSOlympia2FRoomsGiovanniText:
	text_asm
	ld hl, SSOlympia2FRoomsTrainerHeader1
	call TalkToTrainer
	jp TextScriptEnd

SSOlympia2FRoomsLoreleiText:
	text_asm
	ld hl, SSOlympia2FRoomsTrainerHeader2
	call TalkToTrainer
	jp TextScriptEnd


SSOlympia2FRoomsNormanBattleText:
	text_far _SSOlympia2FRoomsNormanBattleText
	text_end

SSOlympia2FRoomsNormanEndBattleText:
	text_far _SSOlympia2FRoomsNormanEndBattleText
	text_end

SSOlympia2FRoomsNormanAfterBattleText:
	text_far _SSOlympia2FRoomsNormanAfterBattleText
	text_end

SSOlympia2FRoomsGiovanniBattleText:
	text_far _SSOlympia2FRoomsGiovanniBattleText
	text_end

SSOlympia2FRoomsGiovanniEndBattleText:
	text_far _SSOlympia2FRoomsGiovanniEndBattleText
	text_end

SSOlympia2FRoomsGiovanniAfterBattleText:
	text_far _SSOlympia2FRoomsGiovanniAfterBattleText
	text_end

SSOlympia2FRoomsLoreleiBattleText:
	text_far _SSOlympia2FRoomsLoreleiBattleText
	text_end

SSOlympia2FRoomsLoreleiEndBattleText:
	text_far _SSOlympia2FRoomsLoreleiEndBattleText
	text_end

SSOlympia2FRoomsLoreleiAfterBattleText:
	text_far _SSOlympia2FRoomsLoreleiAfterBattleText
	text_end

SSOlympia2FRoomsPokemaniacText:
	text_asm
	ld hl, SSOlympia2FRoomsTrainerHeader3
	call TalkToTrainer
	jp TextScriptEnd

SSOlympia2FRoomsPokemaniacBattleText:
	text_far _SSOlympia2FRoomsPokemaniacBattleText
	text_end

SSOlympia2FRoomsPokemaniacEndBattleText:
	text_far _SSOlympia2FRoomsPokemaniacEndBattleText
	text_end

SSOlympia2FRoomsPokemaniacAfterBattleText:
	text_far _SSOlympia2FRoomsPokemaniacAfterBattleText
	text_end

SSOlympia2FRoomsGamblerText:
	text_asm
	ld hl, SSOlympia2FRoomsTrainerHeader4
	call TalkToTrainer
	jp TextScriptEnd

SSOlympia2FRoomsGamblerBattleText:
	text_far _SSOlympia2FRoomsGamblerBattleText
	text_end

SSOlympia2FRoomsGamblerEndBattleText:
	text_far _SSOlympia2FRoomsGamblerEndBattleText
	text_end

SSOlympia2FRoomsGamblerAfterBattleText:
	text_far _SSOlympia2FRoomsGamblerAfterBattleText
	text_end
