#!/usr/bin/env python3
"""
Generate MUTAGENSTONE.md from docs/data/pokemon.json (itself generated by
docs/data/build.py from data/pokemon/mutagen_movesets.asm) so the doc can
never drift from the actual curated table.

Run docs/data/build.py first if mutagen_movesets.asm has changed since the
JSON was last regenerated.

Usage:
    python3 tools/gen_mutagenstone_md.py
"""
import json
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The source file's own section comments, mapped to a reader-facing group.
# The dozen-odd "reduced list, Nth batch" headers are development-process
# markers (this table was filled in over many sessions) with no meaning to
# someone reading the finished result, so they -- and the small "curated
# ahead of the ship" batch -- all fold into one alphabetical "everything
# else" section instead of reproducing curation history.
SECTION_MAP = {
    "S.S. Olympia, the 16 named trainers": "S.S. Olympia's Named Trainers",
    "S.S. Olympia, the 24 NPC classes": "S.S. Olympia's NPC Trainer Classes",
    "the S.S. Olympia's own clearing-prize mutants": "The Ship's Own Mutants",
}
CATCH_ALL = "Every Other Curated Species"


def load_species_sections():
    text = (ROOT / "data/pokemon/mutagen_movesets.asm").read_text()
    section = CATCH_ALL
    sections = {}
    for line in text.splitlines():
        header = re.match(r"; --- (.+?) ---", line)
        if header:
            section = SECTION_MAP.get(header.group(1), CATCH_ALL)
            continue
        row = re.match(r"\tmutagen_moveset (\w+),", line)
        if row:
            sections[row.group(1)] = section
    return sections


def main():
    data = json.loads((ROOT / "docs/data/pokemon.json").read_text())
    sections = load_species_sections()

    groups = {}
    for sp, sect in sections.items():
        groups.setdefault(sect, []).append(sp)

    lines = [
        "# Mutagenstone Movesets",
        "",
        "A Mutagenstone jumps a party Pokemon straight to level 100. Left to itself,",
        "the game hands it whatever the last five entries of its own level-up learnset",
        "happen to be -- which is rarely the moveset that species actually wants. The",
        "rows below override that with a hand-picked five-move kit, one per eligible",
        "species.",
        "",
        "**Every row here is curated by hand, never auto-generated from a template.**",
        "The same table backs two things: your own mutagenated party Pokemon, and the",
        "S.S. Olympia's one-Pokemon trainers (a signature move only has to be written",
        "once, here).",
        "",
        "Only a species' **final evolution** gets its own row -- a pre-evolution stoned",
        "today falls back to the generic behavior above, since Mutagenstone levels a mon",
        "up but doesn't evolve it (yet). Species that can never evolve past themselves,",
        "or that evolve only by trade/stone rather than level, count as their own \"final\"",
        "form for this purpose (e.g. Gloom has its own row, distinct from Vileplume's).",
        "",
        f"**{sum(len(v) for v in groups.values())} species curated.** Browse the same data",
        "interactively -- with full level-up/TM/HM movepools, type coverage, and a",
        "Ghost-form sprite preview for the species that support it -- in the",
        "[Team Builder](https://gloriousorange.github.io/Pokemon-Blue-Nemesis/).",
        "",
    ]

    ordered_groups = list(SECTION_MAP.values()) + [CATCH_ALL]
    for group in ordered_groups:
        members = groups.get(group)
        if not members:
            continue
        lines.append(f"## {group} ({len(members)})")
        lines.append("")
        lines.append("| Species | Move 1 | Move 2 | Move 3 | Move 4 | Move 5 |")
        lines.append("|---|---|---|---|---|---|")

        ordered = members if group != CATCH_ALL else sorted(
            members, key=lambda sp: data["species"][sp]["display_name"]
        )
        for sp in ordered:
            rec = data["species"][sp]
            moves = rec["mutagen_moveset"]
            move_names = [data["moves"][m]["display_name"] for m in moves]
            lines.append(f"| {rec['display_name']} | " + " | ".join(move_names) + " |")
        lines.append("")

    out = ROOT / "MUTAGENSTONE.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} -- {sum(len(v) for v in groups.values())} species across {len(ordered_groups)} sections")


if __name__ == "__main__":
    main()
